Update vext

diff --git a/vext b/vext
--- a/vext
+++ b/vext
@@ -62,7 +62,7 @@ if [ -z "$sml" ]; then
 
 ERROR: No supported SML compiler or interpreter found       
 EOF
-	cat <<EOF
+	cat 1>&2 <<EOF
 
   The Vext external source code manager needs a Standard ML (SML)
   compiler or interpreter to run.
@@ -90,7 +90,7 @@ fi
 arglist=""
 for arg in "$@"; do
     if [ -n "$arglist" ]; then arglist="$arglist,"; fi
-    if echo "$arg" | grep -q '[^a-z]' ; then
+    if echo "$arg" | grep -q '["'"'"']' ; then
 	arglist="$arglist\"usage\""
     else
 	arglist="$arglist\"$arg\""
@@ -110,6 +110,7 @@ case "$sml" in
         fi ;;
     mlton)
         if [ ! -x "$gen_out" ]; then
+	    echo "[Precompiling Vext binary...]" 1>&2
 	    echo "val _ = main ()" | cat "$program" - > "$gen_sml"
 	    mlton -output "$gen_out" "$gen_sml"
         fi
@@ -141,7 +142,7 @@ EOF
             ) > "$gen_sml"
 	CM_VERBOSE=false sml "$gen_sml" ;;
     *)
-	echo "Unknown SML implementation name: $sml";
+	echo "ERROR: Unknown SML implementation name: $sml" 1>&2;
 	exit 2 ;;
 esac
        
