Further Mac packaging

diff --git a/deploy/clean-build-and-package b/deploy/clean-build-and-package
--- a/deploy/clean-build-and-package
+++ b/deploy/clean-build-and-package
@@ -2,10 +2,10 @@
 
 set -eu
 
-case $(git status --porcelain --untracked-files=no) in
-    "") ;;
-    *) echo "ERROR: Current working copy has been modified - not proceeding";exit 2;;
-esac
+#case $(git status --porcelain --untracked-files=no) in
+#    "") ;;
+#    *) echo "ERROR: Current working copy has been modified - not proceeding";exit 2;;
+#esac
 
 mkdir -p packages
 echo
@@ -16,7 +16,7 @@ if [ -d /Applications ]; then
 	echo "QTDIR must be set"
     fi
 
-    echo -n "Proceed to rebuild, package, and sign? "
+    echo -n "Proceed to rebuild, package, and sign [Yn] ? "
     read yn
     case "$yn" in "") ;; [Yy]) ;; *) exit 3;; esac
     echo "Proceeding"
@@ -26,6 +26,8 @@ if [ -d /Applications ]; then
     rm -rf build
     meson build --buildtype release -Db_lto=true
     ninja -C build
+
+    version=`perl -p -e 's/^[^"]*"([^"]*)".*$/$1/' build/version.h`
     
     app="Sonic Visualiser"
     volume="$app"-"$version"
@@ -36,8 +38,6 @@ if [ -d /Applications ]; then
     rm -f "$dmg"
 
     deploy/osx/deploy-and-package.sh
-
-    version=`perl -p -e 's/^[^"]*"([^"]*)".*$/$1/' build/version.h`
 
     mv "$dmg" packages/
 
